### ISSUE TITLE
perhaps a few too many dependencies?

### ISSUE THREAD

**Issue by Pomax** [sindresorhus/clear-cli#1]
Your library literally only needs to send the ANSI `CSI 2 J ` command to a raw filestream, but you've written it to achieve this using 540000 bytes of dependency code =)

As an improvement, may I suggest removing all those dependencies and simply writing the ANSI string needed:
```
let clearCode = '\033[2J';
if (process.platform === "win32") {
  clearCode = '\033c';
}
process.stdout.write(clearCode);
```
This removes the need for over half a megabyte of dependencies just to clear the screen, and is even cross-platform (because of course windows needs a different code, why wouldn't it...)

And as the only argument that clear takes is --help, it seems unnecessary to have arg parsing, but since the only response is literally the instruction to just use `clear`, no need for a big parser dependency chain either:

```
if (process.argv.indexOf('--help') > -1) {
  return console.log("Usage: clear\n");
}
...above code here...
```

**Comment by sindresorhus** [comment]
Not a big deal IMHO. It installs in no time. By using `meow` I get consistently nice help and version output for free in all my CLI's. It might be overkill in this situation, but I prefer convenience over absolute minimalism, especially when the overhead is negligible. Dependencies are also deduped, so you only install and store `meow` once for any CLI using it.

> and is even cross-platform (because of course windows needs a different code, why wouldn't it...)

The current escape has been tested to work on Windows.

**Comment by Pomax** [comment]
If half a meg of unused dependencies that cannot be tree-shaken back out of of a codebase, for running a task that can run identically with only a few lines of code , is something you consider no big deal, then all I can say is that we work in very different worlds indeed.
