### ISSUE TITLE
trange characters: `[1m%`

### ISSUE THREAD

**Issue by iTonyYo** [sindresorhus/clear-cli#2]
using **Hyper 2.0.0**

![image](https://user-images.githubusercontent.com/5499703/47649944-b95b4800-dbb9-11e8-98ac-ab423eeb749a.png)

@sindresorhus

**Comment by sindresorhus** [comment]
This should be reported on Hyper instead. I'm just using a common ANSI escape code to clear the screen. If that's not working, it's a bug in Hyper or the library it uses for rendering (https://github.com/xtermjs/xterm.js).
